apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dental-clinic-app
  name: dental-clinic-app
  namespace: dental-clinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-clinic-app
  template:
    metadata:
      labels:
        app: dental-clinic-app
    spec:
      containers:
        - name: dental-clinic-app
          image: 412631849473.dkr.ecr.ap-southeast-2.amazonaws.com/dental-clinic-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: VITE_PORT
              value: "3000"
            - name: VITE_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: port-secrets
                  key: VITE_API_BASE_URL

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dental-clinic-app
  name: dental-clinic-app
  namespace: dental-clinic-app
spec:
  type: ClusterIP
  selector:
    app: dental-clinic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dental-clinic-app-ingress
  namespace: dental-clinic-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:412631849473:certificate/e0ade39d-5081-4323-ad45-0c1902873d6c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  rules:
    - host: dental-clinic-app.myprofilely.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dental-clinic-app
                port:
                  number: 80
