name: CI/CD for Dental Clinic Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_id }}-${{ github.sha }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.production file
        run: echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Save Image URI Artifact
        run: echo "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG" > image-uri.txt

      - name: Upload Image URI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-uri
          path: image-uri.txt
          retention-days: 1

  deploy:
    name: Deploy to AWS EKS
    needs: build
    runs-on: ubuntu-latest

    env:
      NAMESPACE: dental-clinic-app
      EKS_CLUSTER_NAME: dental-clinic-cluster
      AWS_REGION: ap-southeast-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve Image URI
        uses: actions/download-artifact@v4
        with:
          name: image-uri
          path: .

      - name: Read Image URI
        run: echo "IMAGE_URI=$(cat image-uri.txt)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Update Deployment YAML with New Image
        run: |
          sed -i "s|image: .*|image: $IMAGE_URI|" k8s/deployment.yml

      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yml

      # - name: Verify Deployment
      #   run: kubectl rollout status deployment/dental-clinic-app -n ${{ env.NAMESPACE }}
